# Generated by Django 4.2.5 on 2023-09-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookings',
            table='bookings',
        ),
    ]
