# Generated by Django 4.2.5 on 2023-10-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_bookings_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name_plural': 'Bookings'},
        ),
    ]
